# Generated by Django 5.0.1 on 2024-03-25 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
